//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IllegalChild
    {
        public long ID { get; set; }
    
        public virtual IllegalPregnant IllegalPregnant { get; set; }
        public virtual Human HumanInfo { get; set; }
    }
}
