//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IllegalPregnant
    {
        public long ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long FemaleHumanID { get; set; }
        public long MaleHumanID { get; set; }
    
        public virtual FemaleHuman Mother { get; set; }
        public virtual MaleHuman Father { get; set; }
        public virtual IllegalChild IllegalChild { get; set; }
    }
}
