//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TWSDataEntities : DbContext
    {
        public TWSDataEntities()
            : base("name=TWSDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Human> Humen { get; set; }
        public virtual DbSet<HumanMarriage> HumanMarriages { get; set; }
        public virtual DbSet<MarriageChild> MarriageChilds { get; set; }
        public virtual DbSet<Pregnant> Pregnants { get; set; }
        public virtual DbSet<IllegalPregnant> IllegalPregnants { get; set; }
        public virtual DbSet<IllegalChild> IllegalChilds { get; set; }
    }
}
